version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: hotel_db
        environment:
            MYSQL_DATABASE: hotel
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data: