version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: spring_hotel
        environment:
            MYSQL_DATABASE: hotel
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data: